version: '3.2'
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    restart: unless-stopped
  database:
    restart: unless-stopped
    container_name: postgresql
    image: postgres
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'customer'
    ports:
      - 5432:5432