version: 2.1

executors:
  gradle:
    docker:
      - image: circleci/openjdk:11-jdk-browsers

jobs:
  lint_and_build:
    executor: gradle
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx1024m
      TERM: dumb
    working_directory: ~/crud-kotlin
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - restore_cache:
          key: crud-kotlin-{{ checksum "build.gradle.kts" }}
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: crud-kotlin-{{ checksum "build.gradle.kts" }}
      - run:
          name: Kotlin Check Lint & Code Smell
          command: gradle clean detekt ktlintCheck --info
      - run:
          name: Gradle Test
          command: gradle test
      - run:
          name: Build
          command: docker build -t ${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} .
workflows:
  version: 2.1
  ci:
    jobs:
      - lint_and_build
